# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kA8d6749CZz1EWj6SNhnOlilM6tRM5L1
"""

! pip install rdkit
import streamlit as st
import pandas as pd
import numpy as np
from rdkit import Chem
from mordred import Calculator, descriptors
import joblib

# --- Configuration de la page ---
st.set_page_config(page_title="Predicteur d'Effets Médicamenteux sur le Microbiote", layout="wide")

# --- A. CHARGEMENT DES COMPOSANTS (Une seule fois au démarrage) ---

@st.cache_resource
def load_components():
    """Charge le modèle, le scaler et les listes de noms à partir des fichiers .joblib."""
    try:
        model = joblib.load('best_et_model.joblib')
        scaler = joblib.load('standard_scaler.joblib')
        feature_names = joblib.load('feature_names.joblib')
        target_names = joblib.load('target_names.joblib')
        return model, scaler, feature_names, target_names
    except FileNotFoundError:
        st.error("Erreur de chargement des fichiers : assurez-vous que tous les fichiers .joblib sont dans le même dossier.")
        st.stop()

# Chargement
model, scaler, feature_names, target_names = load_components()
calc = Calculator(descriptors, ignore_3D=True)


# --- B. FONCTION DE PRÉDICTION PRINCIPALE ---

def make_prediction(smiles):
    """Calcule les descripteurs, met à l'échelle et prédit l'activité."""

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        st.error(f"Le code SMILES '{smiles}' est invalide. Veuillez vérifier le format.")
        return None

    # 1. Calcul de Mordred (Phase 2)
    with st.spinner("Calcul des descripteurs chimiques (Mordred)..."):
        df_features_new = calc.pandas([mol])

    # Nettoyage et conversion
    df_features_new = df_features_new.apply(pd.to_numeric, errors='coerce')
    df_features_new = df_features_new.replace([np.inf, -np.inf], np.nan).fillna(0)

    # 2. Alignement et Mise à l'échelle
    df_features_aligned = pd.DataFrame(columns=feature_names)
    df_features_aligned.loc[0] = 0
    df_features_aligned.update(df_features_new)

    X_new_scaled = scaler.transform(df_features_aligned[feature_names])

    # 3. Prédiction (Phase 3)
    prediction = model.predict(X_new_scaled)[0]

    # 4. Formatage des Résultats
    results_df = pd.DataFrame({
        'Souche Bactérienne': [col.replace('Label_', '').replace('(NT', ' (NT') for col in target_names],
        'Inhibition Prédite': prediction
    })

    return results_df


# --- C. INTERFACE UTILISATEUR STREAMLIT ---

st.title("🔬 **Prédicteur d'Effets sur le Microbiote (Modèle AUROC 0.973)**")
st.markdown("---")
st.markdown("Entrez le code **SMILES** d'un médicament pour prédire son activité inhibitrice sur 40 souches bactériennes intestinales.")

# Champ de saisie pour le SMILES
input_smiles = st.text_input(
    "Code SMILES de la molécule :",
    value='C[C@@H](C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)O', # Exemple du Naproxène par défaut
    help="Exemple : Aspirine -> CC(=O)Oc1ccccc1C(=O)O"
)

# Bouton de lancement
if st.button("LANCER LA PRÉDICTION", type="primary"):
    if input_smiles:
        results_df = make_prediction(input_smiles)

        if results_df is not None:
            total_inhibitions = results_df['Inhibition Prédite'].sum()

            st.markdown("## Résultats")

            if total_inhibitions > 0:
                st.success(f"**Prédiction : Inhibition contre {total_inhibitions} souches bactériennes !**")

                # Affichage des souches actives
                active_results = results_df[results_df['Inhibition Prédite'] == 1].drop(columns=['Inhibition Prédite'])
                st.subheader("Souches prédites comme inhibées :")
                st.dataframe(active_results, hide_index=True)

            else:
                st.info("Le modèle prédit que cette molécule est **inactive** contre toutes les souches testées (p-value > 0.05).")
                st.subheader("Rapport complet (inactif = 0) :")
                st.dataframe(results_df, hide_index=True)

st.markdown("---")
st.markdown("Méthodologie basée sur l'article : *Machine Learning Uncovers Adverse Drug Effects on Intestinal Bacteria* (McCoubrey et al.).")